
  name: pandemic
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Un jeu de plateau sur la propagation de maladies dans le monde.
  description: |
    Ce jeu de plateau se déroule sur une carte représentant les grandes capitales mondiales. 
    Quatre maladies vont se développer dans ces villes. L'objectif des joueurs est de collaborer pour lutter contre la 
    propagation des maladies et si possible les vaincre. 
    Les joueurs pourront effectuer des déplacements, et faire en sorte de diminuer les épidémies afin d'éradiquer les maladies.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  apps:
    run:
      command: usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java PandemicGame
      adapter: none
      environment:
        JAVA_HOME: $SNAP/usr/lib/jvm/default-java
        PATH: $SNAP/usr/lib/jvm/default-java/bin:$PATH
       
  parts:
    local:
        plugin: ant
        source: .
